---

# fork of https://github.com/concourse/influxdb-boshrelease
# includes influxdb 1.4.3 (prometheus support) and bosh linking
- type: replace
  path: /releases/-
  value:
    name: influxdb
    version: 0.1.0-govau
    sha1: c58eecf07c3d86138bb59453b07f78642fd84328
    url: https://github.com/govau/influxdb-boshrelease/releases/download/v0.1.0-govau/influxdb-0.1.0-govau.tgz

- type: replace
  path: /instance_groups/-
  value:
    name: influxdb
    azs:
      - z1
    instances: 1
    vm_type: default
    persistent_disk: 10_240
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: influxdb
        release: influxdb
        provides:
          influxdb: {as: influxdb}
        properties:
          influxdb:
            database: prometheus
            user: ((influxdb_user.username))
            password: ((influxdb_user.password))
            retention: 30d
            http:
              tls:
                enabled: true
                cert: ((influxdb_cert))

# Influxdb username/password
- type: replace
  path: /variables/-
  value:
    name: influxdb_user
    type: user

# Influxdb CA cert
- type: replace
  path: /variables/-
  value:
    name: influxdb_ca_cert
    type: certificate
    options:
      is_ca: true
      common_name: influxdb_ca

- type: replace
  path: /variables/-
  value:
    name: influxdb_cert
    type: certificate
    options:
      ca: influxdb_ca
      common_name: "todo.figure.this.name.out.needs.to.match.bosh.address"
      alternative_names: ["todo.figure.this.name.out.needs.to.match.bosh.address"]
      extended_key_usage: ["server_auth"]
